###
//запрашиваем все строки из БД в формате json
GET http://localhost:8080/api.php?path=/worker
Content-Type: application/json

###
//запрашиваем одину строку из БД с id = 1
GET http://localhost:8080/api.php?path=/worker/1

###
//отправляем новую строку(данные) в БД
//новая трока(новые данные) передаем строкой и присваиваем значения userId='пустое значение'(т.к.генерируется автоматом), userName=Jon и т.д.
POST http://localhost:8080/api.php?path=/worker
Content-Type:  application/json

{"age": "33", "name": "Peter", "surname": "Pan5", "salary": "2345"}

###
//устанавливаем полю с id=9 новые данные
PUT http://localhost:8080/api.php?path=/worker/2
Content-Type:  application/json

{"age": "25", "name": "Peter", "surname": "Parker", "salary": "2345"}

###
//удаляем пользователя с id = 8
DELETE http://localhost:8080/api.php?path=/worker/8

###
//изменяем одно значение из строки БД и вносим изменения
PATCH http://localhost:8080/api.php?path=/worker/12
Content-Type: application/x-www-form-urlencoded

userName=Boris





###
//запрашиваем все данные из БД tasks
GET http://localhost:8080/api.php?path=/task
Content-Type: application/json

###
//запрашиваем одну строку из БД с id=6
GET http://localhost:8080/api.php?path=/task/6

###
//отправляем новые данные
POST http://localhost:8080/api.php?path=/task
Content-Type: application/json

{"title":"task_2", "description": "new_task_2", "status": "new", "deadline_date": "2020-09-30", "deadline_time": "13:00", "worker_id": "10"}

###
//удаляем пользователя с id
DELETE http://localhost:8080/api.php?path=/task/14

###
//устанавливаем для поля с id = 18 новые данные
PUT http://localhost:8080/api.php?path=/task/10
Content-Type: application/json

{"title":"task_20202", "description": "2", "status": "new", "deadline_date": "2020-09-30", "deadline_time": "13:00", "worker_id": "10"}

###
//изменяем одно значение из строки БД и вносим изменения для одного поля с id = 18. При передачи строки с латиницей, пробелами и прочее, необходимо закодировать эту строку. Это зависит от Content-Type
PATCH http://localhost:8080/api.php?path=/task/18
Content-Type: application/x-www-form-urlencoded

deadline=2020-10-30+00%3A00%3A00