###
//запрашиваем все строки из БД в формате json
GET http://localhost:8080/api.php?path=/worker
Content-Type: application/json

###
//запрашиваем одину строку из БД с id = 1
GET http://localhost:8080/api.php?path=/worker/1

###
//отправляем новую строку(данные) в БД в формате x-www-form-urlencoded
//новая трока(новые данные) передаем строкой и присваиваем значения userId='пустое значение'(т.к.генерируется автоматом), userName=Jon и т.д.
POST http://localhost:8080/api.php?path=/worker
Content-Type: application/x-www-form-urlencoded

userId=&userName=Jon&userSurname=Jonson&userAge=22&userSalary=900

###
//устанавливаем полю с id=8 новые данные
PUT http://localhost:8080/api.php?path=/worker/9
Content-Type: application/x-www-form-urlencoded

userId=&userName=Piter&userSurname=Albatros&userAge=23222&userSalary=9000000

###
//удаляем пользователя с id = 8
DELETE http://localhost:8080/api.php?path=/worker/8

###
//изменяем одно значение из строки БД и вносим изменения
PATCH http://localhost:8080/api.php?path=/worker/12
Content-Type: application/x-www-form-urlencoded

userName=Boris





###
//запрашиваем все данные из БД tasks
GET http://localhost:8080/api.php?path=/task
Content-Type: application/json

###
//запрашиваем одну строку из БД с id=6
GET http://localhost:8080/api.php?path=/task/6

###
//отправляем новые данные
POST http://localhost:8080/api.php?path=/task
Content-Type: application/x-www-form-urlencoded

title=task_2&description=new_task_2&status=new&deadline_date=2020-09-30&deadline_time=13:00&worker_id=10

###
//удаляем пользователя с id = 10
DELETE http://localhost:8080/api.php?path=/task/10

###
//устанавливаем для поля с id = 18 новые данные
PUT http://localhost:8080/api.php?path=/task/18
Content-Type: application/x-www-form-urlencoded

title=task_3&description=new_task_3&status=new&deadline_date=2020-10-30&deadline_time=00:00&worker_id=9

###
//изменяем одно значение из строки БД и вносим изменения для одного поля с id = 18. При передачи строки с латиницей, пробелами и прочее, необходимо закодировать эту строку. Это зависит от Content-Type
PATCH http://localhost:8080/api.php?path=/task/18
Content-Type: application/x-www-form-urlencoded

deadline=2020-10-30+00%3A00%3A00